<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddDefaultReports extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $reortData =  array(
            [
                "reportName"=> "Employee Personal Information Report",
                "outputMethod"=> "pdf",
                "pageSize"=> 20,
                "targetKeys"=>json_encode( ["firstName","lastName","dateOfBirth","nationality","gender","maritalStatus","employeeNumber"]),
                "selectedTables"=>json_encode([

                    [
                    'key' => 'firstName',
                    'isDerived' => false,
                    'tableName' => 'employee',
                    'originalTableName' => 'employee',
                    'parentColumnName' => 'firstName',
                    'columnName' => 'firstName',
                    'displayName' => 'First Name',
                    'columnIndex' => 0,
                    'valueType' => 'text',
                    'dataIndex' => 'employeefirstName',
                        
                    ],
                    
                    [
                        'key' => 'lastName',
                        'isDerived' => false,
                        'tableName' => 'employee',
                        'originalTableName' => 'employee',
                        'parentColumnName' => 'lastName',
                        'columnName' => 'lastName',
                        'displayName' => 'Last Name',
                        'columnIndex' => 1,
                        'valueType' => 'text',
                        'dataIndex' => 'employeelastName',
                    ],
                    [
                        'key' => 'dateOfBirth',
                        'isDerived' => false,
                        'tableName' => 'employee',
                        'originalTableName' => 'employee',
                        'parentColumnName' => 'dateOfBirth',
                        'columnName' => 'dateOfBirth',
                        'displayName' => 'Date of Birth',
                        'columnIndex' => 2,
                        'valueType' => 'text',
                        'dataIndex' => 'employeedateOfBirth',
                    ],
                    [
                        'key' => 'nationality',
                        'isDerived' => false,
                        'originalTableName' => 'employee',
                        'tableName' => 'personalnationality',
                        'parentColumnName' => 'nationalityId',
                        'columnName' => 'name',
                        'displayName' => 'Nationality',
                        'columnIndex' => 3,
                        'valueType' => 'text',
                        'dataIndex' => 'personalnationalityname',
                    ],
                    [
                        'key' => 'gender',
                        'isDerived' => false,
                        'originalTableName' => 'employee',
                        'tableName' => 'personalgender',
                        'parentColumnName' => 'genderId',
                        'columnName' => 'name',
                        'displayName' => 'Gender',
                        'columnIndex' => 4,
                        'valueType' => 'text', 
                    ],
                    [
                        'key' => 'maritalStatus',
                        'isDerived' => false,
                        'originalTableName' => 'employee',
                        'tableName' => 'personalmaritalStatus',
                        'parentColumnName' => 'maritalStatusId',
                        'columnName' => 'name',
                        'displayName' => 'Marital Status',
                        'columnIndex' => 5,
                        'valueType' => 'text',
                        'dataIndex' => 'personalmaritalStatusname', 
                    ],
                    [
                        'key' => 'employeeNumber',
                        'isDerived' => false,
                        'tableName' => 'employee',
                        'originalTableName' => 'employee',
                        'parentColumnName' => 'employeeNumber',
                        'columnName' => 'employeeNumber',
                        'displayName' => 'Employee Number',
                        'columnIndex' => 6,
                        'valueType' => 'text',
                        'dataIndex' => 'employeeemployeeNumber',
                    ]

                ]),
                "joinCriterias"=>json_encode([
                   [
                    'tableOneName' => 'employee',
                    'tableOneAlias' => 'employee',
                    'tableOneOperandOne' => 'nationalityId',
                    'operator' => '=',
                    'tableTwoName' => 'nationality',
                    'tableTwoOperandOne' => 'id',
                    'tableTwoAlias' => 'personalnationality',
                   ],
                   [    'tableOneName' => 'employee',
                   'tableOneAlias' => 'employee',
                   'tableOneOperandOne' => 'genderId',
                   'operator' => '=',
                   'tableTwoName' => 'gender',
                   'tableTwoOperandOne' => 'id',
                   'tableTwoAlias' => 'personalgender',  
                ],
                [
                    'tableOneName' => 'employee',
                    'tableOneAlias' => 'employee',
                    'tableOneOperandOne' => 'maritalStatusId',
                    'operator' => '=',
                    'tableTwoName' => 'maritalStatus',
                    'tableTwoOperandOne' => 'id',
                    'tableTwoAlias' => 'personalmaritalStatus',  
                ]
                ]),
                "hideDetailedData"=>false,
                'createdBy' => null,
                'updatedBy' => null,
                'createdAt' => DB::raw('CURRENT_TIMESTAMP'),
                'updatedAt' => DB::raw('CURRENT_TIMESTAMP'),
                "isSystemReport"=>true,
                "id"=>2,
                "isChartAvailable"=> false,
                "chartType"=> "pieChart",
                "aggregateType"=> null,
                "aggregateField"=> null,
                "showSummeryTable"=> false,
                "groupBy"=> json_encode([]),
            ],
            [
                "reportName"=> "Contact Information Report",
                "outputMethod"=> "pdf",
                "pageSize"=> 20,
                "targetKeys"=>json_encode( ["workEmail","personalEmail","workPhone","mobilePhone","homePhone","lastName","employeeNumber","firstName"]),
                "selectedTables"=>json_encode([
                   [
                        'key' => 'workEmail',
                        'isDerived' => false,
                        'tableName' => 'employee',
                        'originalTableName' => 'employee',
                        'parentColumnName' => 'workEmail',
                        'columnName' => 'workEmail',
                        'displayName' => 'Work Email',
                        'columnIndex' => 0,
                        'valueType' => 'text',
                        'dataIndex' => 'employeeworkEmail',
                      ],
                    [
                        'key' => 'personalEmail',
                        'isDerived' => false,
                        'tableName' => 'employee',
                        'originalTableName' => 'employee',
                        'parentColumnName' => 'personalEmail',
                        'columnName' => 'personalEmail',
                        'displayName' => 'Personal Email',
                        'columnIndex' => 1,
                        'valueType' => 'text',
                        'dataIndex' => 'employeepersonalEmail',
                      ],
                     [
                        'key' => 'workPhone',
                        'isDerived' => false,
                        'tableName' => 'employee',
                        'originalTableName' => 'employee',
                        'parentColumnName' => 'workPhone',
                        'columnName' => 'workPhone',
                        'displayName' => 'Work-phone',
                        'columnIndex' => 2,
                        'valueType' => 'text',
                        'dataIndex' => 'employeeworkPhone',
                      ],
                       [
                        'key' => 'mobilePhone',
                        'isDerived' => false,
                        'tableName' => 'employee',
                        'originalTableName' => 'employee',
                        'parentColumnName' => 'mobilePhone',
                        'columnName' => 'mobilePhone',
                        'displayName' => 'Mobile-phone',
                        'columnIndex' => 3,
                        'valueType' => 'text',
                        'dataIndex' => 'employeemobilePhone',
                      ],
                      [
                        'key' => 'homePhone',
                        'isDerived' => false,
                        'tableName' => 'employee',
                        'originalTableName' => 'employee',
                        'parentColumnName' => 'homePhone',
                        'columnName' => 'homePhone',
                        'displayName' => 'Home-phone',
                        'columnIndex' => 4,
                        'valueType' => 'text',
                        'dataIndex' => 'employeehomePhone',
                      ],
                     [
                        'key' => 'lastName',
                        'isDerived' => false,
                        'tableName' => 'employee',
                        'originalTableName' => 'employee',
                        'parentColumnName' => 'lastName',
                        'columnName' => 'lastName',
                        'displayName' => 'Last Name',
                        'columnIndex' => 5,
                        'valueType' => 'text',
                        'dataIndex' => 'employeelastName',
                      ],
                      [
                        'key' => 'employeeNumber',
                        'isDerived' => false,
                        'tableName' => 'employee',
                        'originalTableName' => 'employee',
                        'parentColumnName' => 'employeeNumber',
                        'columnName' => 'employeeNumber',
                        'displayName' => 'Employee Number',
                        'columnIndex' => 6,
                        'valueType' => 'text',
                        'dataIndex' => 'employeeemployeeNumber',
                      ],
                       [
                        'key' => 'firstName',
                        'isDerived' => false,
                        'tableName' => 'employee',
                        'originalTableName' => 'employee',
                        'parentColumnName' => 'firstName',
                        'columnName' => 'firstName',
                        'displayName' => 'First Name',
                        'columnIndex' => 7,
                        'valueType' => 'text',
                        'dataIndex' => 'employeefirstName',
                      ],
                   

                ]),
                "joinCriterias"=>json_encode([
                   
                ]),
                "hideDetailedData"=>false,
                'createdBy' => null,
                'updatedBy' => null,
                'createdAt' => DB::raw('CURRENT_TIMESTAMP'),
                'updatedAt' => DB::raw('CURRENT_TIMESTAMP'),
                "isSystemReport"=>true,
                "id"=>3,
                "isChartAvailable"=> false,
                "chartType"=> "pieChart",
                "aggregateType"=> null,
                "aggregateField"=> null,
                "showSummeryTable"=> false,
                "groupBy"=> json_encode([]),
            ],

            [
                "reportName"=> "Employment History Report",
                "outputMethod"=> "pdf",
                "pageSize"=> 20,
                "targetKeys"=>json_encode(["employeeNumber","firstName","lastName","hireDate","employments.effectiveDate","employments.employmentStatus","employments.comment"] ),
                "selectedTables"=>json_encode(
                    [
                        [
                          'key' => 'employeeNumber',
                          'isDerived' => false,
                          'tableName' => 'employee',
                          'originalTableName' => 'employee',
                          'parentColumnName' => 'employeeNumber',
                          'columnName' => 'employeeNumber',
                          'displayName' => 'Employee Number',
                          'columnIndex' => 0,
                          'valueType' => 'text',
                          'dataIndex' => 'employeeemployeeNumber',
                        ],
                        [
                          'key' => 'firstName',
                          'isDerived' => false,
                          'tableName' => 'employee',
                          'originalTableName' => 'employee',
                          'parentColumnName' => 'firstName',
                          'columnName' => 'firstName',
                          'displayName' => 'First Name',
                          'columnIndex' => 1,
                          'valueType' => 'text',
                          'dataIndex' => 'employeefirstName',
                        ],
                         [
                          'key' => 'lastName',
                          'isDerived' => false,
                          'tableName' => 'employee',
                          'originalTableName' => 'employee',
                          'parentColumnName' => 'lastName',
                          'columnName' => 'lastName',
                          'displayName' => 'Last Name',
                          'columnIndex' => 2,
                          'valueType' => 'text',
                          'dataIndex' => 'employeelastName',
                        ],
                        [
                          'key' => 'hireDate',
                          'isDerived' => false,
                          'tableName' => 'employee',
                          'originalTableName' => 'employee',
                          'parentColumnName' => 'hireDate',
                          'columnName' => 'hireDate',
                          'displayName' => 'Hire Date',
                          'columnIndex' => 3,
                          'valueType' => 'text',
                          'dataIndex' => 'employeehireDate',
                        ],
                         [
                          'key' => 'employments.effectiveDate',
                          'isDerived' => false,
                          'tableName' => 'employeeEmployment',
                          'originalTableName' => 'employeeEmployment',
                          'parentColumnName' => 'effectiveDate',
                          'columnName' => 'effectiveDate',
                          'displayName' => 'Employments Effective Date',
                          'columnIndex' => 4,
                          'valueType' => 'text',
                          'dataIndex' => 'employeeEmploymenteffectiveDate',
                        ],
                        [
                          'key' => 'employments.employmentStatus',
                          'isDerived' => false,
                          'tableName' => 'employmentsemploymentStatus',
                          'originalTableName' => 'employeeEmployment',
                          'parentColumnName' => 'employmentStatus',
                          'columnName' => 'name',
                          'displayName' => 'Employments Employment Status',
                          'columnIndex' => 5,
                          'valueType' => 'text',
                          'dataIndex' => 'employmentsemploymentStatusname',
                        ],
                        [
                          'key' => 'employments.comment',
                          'isDerived' => false,
                          'tableName' => 'employeeEmployment',
                          'originalTableName' => 'employeeEmployment',
                          'parentColumnName' => 'comment',
                          'columnName' => 'comment',
                          'displayName' => 'Employments Comment',
                          'columnIndex' => 6,
                          'valueType' => 'text',
                          'dataIndex' => 'employeeEmploymentcomment',
                        ],
                      ]
                   

                ),
                "joinCriterias"=>json_encode([
                    [
                         [
                          'tableOneName' => 'employee',
                          'tableOneAlias' => 'employee',
                          'tableOneOperandOne' => 'id',
                          'tableOneOperandTwo' => 'currentEmploymentsId',
                          'operator' => '=',
                          'tableTwoName' => 'employeeEmployment',
                          'tableTwoAlias' => 'employeeEmployment',
                          'tableTwoOperandOne' => 'employeeId',
                          'tableTwoOperandTwo' => 'id',
                        ],
                         [
                          'tableOneName' => 'employeeEmployment',
                          'tableOneAlias' => 'employeeEmployment',
                          'tableOneOperandOne' => 'employmentStatusId',
                          'operator' => '=',
                          'tableTwoName' => 'employmentStatus',
                          'tableTwoAlias' => 'employmentsemploymentStatus',
                          'tableTwoOperandOne' => 'id',
                        ],
                      ]
                   
                ]),
                "hideDetailedData"=>false,
                'createdBy' => null,
                'updatedBy' => null,
                'createdAt' => DB::raw('CURRENT_TIMESTAMP'),
                'updatedAt' => DB::raw('CURRENT_TIMESTAMP'),
                "isSystemReport"=>true,
                "id"=>4,
                "isChartAvailable"=> false,
                "chartType"=> "pieChart",
                "aggregateType"=> null,
                "aggregateField"=> null,
                "showSummeryTable"=> false,
                "groupBy"=> json_encode([]),
            ],
            [
                "reportName"=> "Job History Report",
                "outputMethod"=> "pdf",
                "pageSize"=> 20,
                "targetKeys"=>json_encode( ["employeeNumber","firstName","lastName","jobs.effectiveDate","jobs.location","jobs.department","jobs.division","jobs.jobTitle","jobs.reportsToEmployee"]),
                "selectedTables"=>json_encode([
                     [
                      'key' => 'employeeNumber',
                      'isDerived' => false,
                      'tableName' => 'employee',
                      'originalTableName' => 'employee',
                      'parentColumnName' => 'employeeNumber',
                      'columnName' => 'employeeNumber',
                      'displayName' => 'Employee Number',
                      'columnIndex' => 0,
                      'valueType' => 'text',
                      'dataIndex' => 'employeeemployeeNumber',
                    ],
                     [
                      'key' => 'firstName',
                      'isDerived' => false,
                      'tableName' => 'employee',
                      'originalTableName' => 'employee',
                      'parentColumnName' => 'firstName',
                      'columnName' => 'firstName',
                      'displayName' => 'First Name',
                      'columnIndex' => 1,
                      'valueType' => 'text',
                      'dataIndex' => 'employeefirstName',
                    ],
                     [
                      'key' => 'lastName',
                      'isDerived' => false,
                      'tableName' => 'employee',
                      'originalTableName' => 'employee',
                      'parentColumnName' => 'lastName',
                      'columnName' => 'lastName',
                      'displayName' => 'Last Name',
                      'columnIndex' => 2,
                      'valueType' => 'text',
                      'dataIndex' => 'employeelastName',
                    ],
                    [
                      'key' => 'jobs.effectiveDate',
                      'isDerived' => false,
                      'tableName' => 'employeeJob',
                      'originalTableName' => 'employeeJob',
                      'parentColumnName' => 'effectiveDate',
                      'columnName' => 'effectiveDate',
                      'displayName' => 'Jobs Effective Date',
                      'columnIndex' => 3,
                      'valueType' => 'text',
                      'dataIndex' => 'employeeJobeffectiveDate',
                    ],
                    [
                      'key' => 'jobs.location',
                      'isDerived' => false,
                      'tableName' => 'jobslocation',
                      'originalTableName' => 'employeeJob',
                      'parentColumnName' => 'location',
                      'columnName' => 'name',
                      'displayName' => 'Jobs Location',
                      'columnIndex' => 4,
                      'valueType' => 'text',
                      'dataIndex' => 'jobslocationname',
                    ],
                    [
                      'key' => 'jobs.department',
                      'isDerived' => false,
                      'tableName' => 'jobsdepartment',
                      'originalTableName' => 'employeeJob',
                      'parentColumnName' => 'department',
                      'columnName' => 'name',
                      'displayName' => 'Jobs Department',
                      'columnIndex' => 5,
                      'valueType' => 'text',
                      'dataIndex' => 'jobsdepartmentname',
                    ],
                     [
                      'key' => 'jobs.division',
                      'isDerived' => false,
                      'tableName' => 'jobsdivision',
                      'originalTableName' => 'employeeJob',
                      'parentColumnName' => 'division',
                      'columnName' => 'name',
                      'displayName' => 'Jobs Division',
                      'columnIndex' => 6,
                      'valueType' => 'text',
                      'dataIndex' => 'jobsdivisionname',
                    ],
                    [
                      'key' => 'jobs.jobTitle',
                      'isDerived' => false,
                      'tableName' => 'jobsjobTitle',
                      'originalTableName' => 'employeeJob',
                      'parentColumnName' => 'jobTitle',
                      'columnName' => 'name',
                      'displayName' => 'Jobs Job Title',
                      'columnIndex' => 7,
                      'valueType' => 'text',
                      'dataIndex' => 'jobsjobTitlename',
                    ],
                    [
                      'key' => 'jobs.reportsToEmployee',
                      'isDerived' => true,
                      'tableName' => 'jobsreportsToEmployee',
                      'originalTableName' => 'employeeJob',
                      'parentColumnName' => 'reportsToEmployee',
                      'columnName' => 'fullName',
                      'displayName' => 'Jobs Reports-to',
                      'columnIndex' => 8,
                      'valueType' => 'text',
                      'dataIndex' => 'jobsreportsToEmployeefullName',
                    ],
                  ]),
                "joinCriterias"=>json_encode([
                 [
                      'tableOneName' => 'employee',
                      'tableOneAlias' => 'employee',
                      'tableOneOperandOne' => 'id',
                      'tableOneOperandTwo' => 'currentJobsId',
                      'operator' => '=',
                      'tableTwoName' => 'employeeJob',
                      'tableTwoAlias' => 'employeeJob',
                      'tableTwoOperandOne' => 'employeeId',
                      'tableTwoOperandTwo' => 'id',
                    ],
                    [
                      'tableOneName' => 'employeeJob',
                      'tableOneAlias' => 'employeeJob',
                      'tableOneOperandOne' => 'locationId',
                      'operator' => '=',
                      'tableTwoName' => 'location',
                      'tableTwoAlias' => 'jobslocation',
                      'tableTwoOperandOne' => 'id',
                    ],
                    [
                      'tableOneName' => 'employeeJob',
                      'tableOneAlias' => 'employeeJob',
                      'tableOneOperandOne' => 'departmentId',
                      'operator' => '=',
                      'tableTwoName' => 'department',
                      'tableTwoAlias' => 'jobsdepartment',
                      'tableTwoOperandOne' => 'id',
                    ],
                    [
                      'tableOneName' => 'employeeJob',
                      'tableOneAlias' => 'employeeJob',
                      'tableOneOperandOne' => 'divisionId',
                      'operator' => '=',
                      'tableTwoName' => 'division',
                      'tableTwoAlias' => 'jobsdivision',
                      'tableTwoOperandOne' => 'id',
                    ],
                    [
                      'tableOneName' => 'employeeJob',
                      'tableOneAlias' => 'employeeJob',
                      'tableOneOperandOne' => 'jobTitleId',
                      'operator' => '=',
                      'tableTwoName' => 'jobTitle',
                      'tableTwoAlias' => 'jobsjobTitle',
                      'tableTwoOperandOne' => 'id',
                    ],
                    [
                      'tableOneName' => 'employeeJob',
                      'tableOneAlias' => 'employeeJob',
                      'tableOneOperandOne' => 'reportsToEmployeeId',
                      'operator' => '=',
                      'tableTwoName' => 'employee',
                      'tableTwoAlias' => 'jobsreportsToEmployee',
                      'tableTwoOperandOne' => 'id',
                    ],
                  ]),
                "hideDetailedData"=>false,
                'createdBy' => null,
                'updatedBy' => null,
                'createdAt' => DB::raw('CURRENT_TIMESTAMP'),
                'updatedAt' => DB::raw('CURRENT_TIMESTAMP'),
                "isSystemReport"=>true,
                "id"=>5,
                "isChartAvailable"=> false,
                "chartType"=> "pieChart",
                "aggregateType"=> null,
                "aggregateField"=> null,
                "showSummeryTable"=> false,
                "groupBy"=> json_encode([]),
            ],
            [
                "reportName"=> "Job vs Salary Summery",
                "outputMethod"=> "pdf",
                "pageSize"=> 20,
                "targetKeys"=>json_encode(["jobs.jobTitle","salaries.basic"] ),
                "selectedTables"=>json_encode([
                     [
                      'key' => 'jobs.jobTitle',
                      'isDerived' => false,
                      'tableName' => 'jobsjobTitle',
                      'originalTableName' => 'employeeJob',
                      'parentColumnName' => 'jobTitle',
                      'columnName' => 'name',
                      'displayName' => 'Jobs Job Title',
                      'columnIndex' => 0,
                      'valueType' => 'text',
                      'dataIndex' => 'jobsjobTitlename',
                    ],
                    [
                      'key' => 'salaries.basic',
                      'isDerived' => false,
                      'tableName' => 'employeeSalary',
                      'originalTableName' => 'employeeSalary',
                      'parentColumnName' => 'basic',
                      'columnName' => 'basic',
                      'displayName' => 'Salaries Basic',
                      'columnIndex' => 1,
                      'valueType' => 'text',
                      'dataIndex' => 'employeeSalarybasic',
                    ],
                  ]),
                "joinCriterias"=>json_encode([
                    [
                      'tableOneName' => 'employee',
                      'tableOneAlias' => 'employee',
                      'tableOneOperandOne' => 'id',
                      'tableOneOperandTwo' => 'currentJobsId',
                      'operator' => '=',
                      'tableTwoName' => 'employeeJob',
                      'tableTwoAlias' => 'employeeJob',
                      'tableTwoOperandOne' => 'employeeId',
                      'tableTwoOperandTwo' => 'id',
                    ],
                    [
                      'tableOneName' => 'employeeJob',
                      'tableOneAlias' => 'employeeJob',
                      'tableOneOperandOne' => 'jobTitleId',
                      'operator' => '=',
                      'tableTwoName' => 'jobTitle',
                      'tableTwoAlias' => 'jobsjobTitle',
                      'tableTwoOperandOne' => 'id',
                    ],
                    [
                      'tableOneName' => 'employee',
                      'tableOneAlias' => 'employee',
                      'tableOneOperandOne' => 'id',
                      'tableOneOperandTwo' => 'currentSalariesId',
                      'operator' => '=',
                      'tableTwoName' => 'employeeSalary',
                      'tableTwoAlias' => 'employeeSalary',
                      'tableTwoOperandOne' => 'employeeId',
                      'tableTwoOperandTwo' => 'id',
                    ],
                  ]),
                "hideDetailedData"=>false,
                'createdBy' => null,
                'updatedBy' => null,
                'createdAt' => DB::raw('CURRENT_TIMESTAMP'),
                'updatedAt' => DB::raw('CURRENT_TIMESTAMP'),
                "isSystemReport"=>true,
                "groupBy"=>json_encode(["jobsjobTitlename"]),
                "isChartAvailable"=>true,
                "chartType"=> "pieChart",
                "aggregateField"=> "employeeSalarybasic",
                "aggregateType"=> "count",
                "id"=>6,
                "showSummeryTable"=> false,
            ],  
            [
                "reportName"=> "Salary History",
                "outputMethod"=> "pdf",
                "pageSize"=> 20,
                "targetKeys"=>json_encode( ["employeeNumber","firstName","lastName","salaries.effectiveDate","salaries.basic","salaries.allowance","salaries.epfEmployer","salaries.epfEmployee","salaries.etf","salaries.payeeTax","salaries.ctc"]),
                "selectedTables"=>json_encode([
                    [
                      'key' => 'employeeNumber',
                      'isDerived' => false,
                      'tableName' => 'employee',
                      'originalTableName' => 'employee',
                      'parentColumnName' => 'employeeNumber',
                      'columnName' => 'employeeNumber',
                      'displayName' => 'Employee Number',
                      'columnIndex' => 0,
                      'valueType' => 'text',
                      'dataIndex' => 'employeeemployeeNumber',
                    ],
                     [
                      'key' => 'firstName',
                      'isDerived' => false,
                      'tableName' => 'employee',
                      'originalTableName' => 'employee',
                      'parentColumnName' => 'firstName',
                      'columnName' => 'firstName',
                      'displayName' => 'First Name',
                      'columnIndex' => 1,
                      'valueType' => 'text',
                      'dataIndex' => 'employeefirstName',
                    ],
                    [
                      'key' => 'lastName',
                      'isDerived' => false,
                      'tableName' => 'employee',
                      'originalTableName' => 'employee',
                      'parentColumnName' => 'lastName',
                      'columnName' => 'lastName',
                      'displayName' => 'Last Name',
                      'columnIndex' => 2,
                      'valueType' => 'text',
                      'dataIndex' => 'employeelastName',
                    ],
                    [
                      'key' => 'salaries.effectiveDate',
                      'isDerived' => false,
                      'tableName' => 'employeeSalary',
                      'originalTableName' => 'employeeSalary',
                      'parentColumnName' => 'effectiveDate',
                      'columnName' => 'effectiveDate',
                      'displayName' => 'Salaries Effective Date',
                      'columnIndex' => 3,
                      'valueType' => 'text',
                      'dataIndex' => 'employeeSalaryeffectiveDate',
                    ],
                    [
                      'key' => 'salaries.basic',
                      'isDerived' => false,
                      'tableName' => 'employeeSalary',
                      'originalTableName' => 'employeeSalary',
                      'parentColumnName' => 'basic',
                      'columnName' => 'basic',
                      'displayName' => 'Salaries Basic',
                      'columnIndex' => 4,
                      'valueType' => 'text',
                      'dataIndex' => 'employeeSalarybasic',
                    ],
                    [
                      'key' => 'salaries.allowance',
                      'isDerived' => false,
                      'tableName' => 'employeeSalary',
                      'originalTableName' => 'employeeSalary',
                      'parentColumnName' => 'allowance',
                      'columnName' => 'allowance',
                      'displayName' => 'Salaries Allowance',
                      'columnIndex' => 5,
                      'valueType' => 'text',
                      'dataIndex' => 'employeeSalaryallowance',
                    ],
                    [
                      'key' => 'salaries.epfEmployer',
                      'isDerived' => false,
                      'tableName' => 'employeeSalary',
                      'originalTableName' => 'employeeSalary',
                      'parentColumnName' => 'epfEmployer',
                      'columnName' => 'epfEmployer',
                      'displayName' => 'Salaries EPF – Employer',
                      'columnIndex' => 6,
                      'valueType' => 'text',
                      'dataIndex' => 'employeeSalaryepfEmployer',
                    ],
                    [
                      'key' => 'salaries.epfEmployee',
                      'isDerived' => false,
                      'tableName' => 'employeeSalary',
                      'originalTableName' => 'employeeSalary',
                      'parentColumnName' => 'epfEmployee',
                      'columnName' => 'epfEmployee',
                      'displayName' => 'Salaries EPF – Employee',
                      'columnIndex' => 7,
                      'valueType' => 'text',
                      'dataIndex' => 'employeeSalaryepfEmployee',
                    ],
                    [
                      'key' => 'salaries.etf',
                      'isDerived' => false,
                      'tableName' => 'employeeSalary',
                      'originalTableName' => 'employeeSalary',
                      'parentColumnName' => 'etf',
                      'columnName' => 'etf',
                      'displayName' => 'Salaries ETF',
                      'columnIndex' => 8,
                      'valueType' => 'text',
                      'dataIndex' => 'employeeSalaryetf',
                    ],
                    [
                      'key' => 'salaries.payeeTax',
                      'isDerived' => false,
                      'tableName' => 'employeeSalary',
                      'originalTableName' => 'employeeSalary',
                      'parentColumnName' => 'payeeTax',
                      'columnName' => 'payeeTax',
                      'displayName' => 'Salaries Payee Tax',
                      'columnIndex' => 9,
                      'valueType' => 'text',
                      'dataIndex' => 'employeeSalarypayeeTax',
                    ],
                    [
                      'key' => 'salaries.ctc',
                      'isDerived' => false,
                      'tableName' => 'employeeSalary',
                      'originalTableName' => 'employeeSalary',
                      'parentColumnName' => 'ctc',
                      'columnName' => 'ctc',
                      'displayName' => 'Salaries CTC',
                      'columnIndex' => 10,
                      'valueType' => 'text',
                      'dataIndex' => 'employeeSalaryctc',
                    ],
                  ]),
                "joinCriterias"=>json_encode([
                     [
                      'tableOneName' => 'employee',
                      'tableOneAlias' => 'employee',
                      'tableOneOperandOne' => 'id',
                      'tableOneOperandTwo' => 'currentSalariesId',
                      'operator' => '=',
                      'tableTwoName' => 'employeeSalary',
                      'tableTwoAlias' => 'employeeSalary',
                      'tableTwoOperandOne' => 'employeeId',
                      'tableTwoOperandTwo' => 'id',
                    ],
                  ]),
                "hideDetailedData"=>false,
                'createdBy' => null,
                'updatedBy' => null,
                'createdAt' => DB::raw('CURRENT_TIMESTAMP'),
                'updatedAt' => DB::raw('CURRENT_TIMESTAMP'),
                "isSystemReport"=>true,
                "id"=>7,
                "isChartAvailable"=> false,
                "chartType"=> "pieChart",
                "aggregateType"=> null,
                "aggregateField"=> null,
                "showSummeryTable"=> false,
                "groupBy"=> json_encode([]),
            ],  

        );

        try {
            $record = DB::table('reportData')->where('id',[2,3,4,5,6,7])->first();

            if ($record) {
                return ('report exists');
            }

            DB::table('reportData')->insert($reortData);
        } catch (\Throwable $th) {
            throw $th;
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        try {
            $record = DB::table('reportData')->where('id', [2,3,4,5,6,7])->first();

            if (empty($record)) {
                return ('report does not exist');
            }

            $affectedRows = DB::table('reportData')->where('id', [2,3,4,5,6,7])->delete();

            return ($affectedRows) ? true : false;
        } catch (\Throwable $th) {
            throw $th;
        }
    }
}
