export default [
  {
    path: '/',
    component: '../layouts/BlankLayout',
    routes: [
      {
        path: '/auth',
        component: '../layouts/UserLayout',
        routes: [
          {
            name: 'login',
            path: '/auth/login',
            component: './Auth/login',
          },
          {
            name: 'forgotPassword',
            path: '/auth/forgotPassword',
            component: './Auth/forgotPassword',
          },
          {
            name: 'sso',
            path: '/auth/sso',
            component: './Auth/sso',
          },
          {
            name: 'passwordWithOptions',
            path: '/auth/password-options/:type/:verificationToken',
            component: './Auth/LoginOptions',
          },
          {
            name: 'verficationTokenNotFound',
            path: '/auth/password-options/not-found',
            component: './404',
          },
        ],
      },
      {
        path: '/',
        component: '../layouts/SecurityLayout',
        routes: [
          {
            path: '/',
            component: '../layouts/BasicLayout',
            authority: ['admin', 'user'],
            routes: [
              {
                path: '/',
                redirect: '/dashboard',
              },
              {
                path: '/dashboard',
                name: 'Dashboard',
                svgIcon: 'Dashboard',
                component: './Dashboard',
              },
              {
                path: '/org-charts',
                name: 'Organization Planning',
                svgIcon: 'OrgCharts',
                access: 'canShowMenuItem',
                permissions: ['org-chart-read', 'manager-org-chart-access'],
                routes: [
                  {
                    path: '/org-charts/department-chart',
                    name: 'Organization Structure',
                    component: './OrgCharts/DepartmentChart',
                    permissions: ['org-chart-read'],
                    access: 'canShowMenuItem',
                  },
                  {
                    path: '/org-charts/organization-chart',
                    name: 'Organization Chart',
                    component: './OrgCharts/ManagerOrgChart',
                    permissions: ['manager-org-chart-access'],
                    access: 'canShowMenuItem',
                  },
                  {
                    path: '/org-charts/employee-chart',
                    name: 'Reporting Structure',
                    component: './OrgCharts/EmployeeChart',
                    permissions: ['org-chart-read'],
                    access: 'canShowMenuItem',
                  },
                ],
              },
              {
                path: '/employees',
                name: 'Profile Management',
                svgIcon: 'Employee',
                access: 'canShowMenuItem',
                permissions: ['employee-write'],
                routes: [
                  {
                    path: '/employees',
                    component: './Employee',
                    name: 'Employee Profiles',
                    access: 'canShowMenuItem',
                    permissions: ['employee-write'],
                  },
                  {
                    path: '/employees/new',
                    hideInMenu: true,
                    name: 'Add Employee',
                    component: './Employee/AddEmployee',
                  },
                  {
                    path: '/employees/:employeeId/document-templates/:templateId',
                    hideInMenu: true,
                    name: 'Employee Document',
                    component: './DocumentTemplate/EmployeeDocument',
                  },
                  {
                    path: '/employees/:id',
                    hideInMenu: true,
                    name: 'Edit Employee',
                    component: './Employee/ParentEditEmployee',
                  },
                ],
              },
              {
                path: '/document',
                name: 'Document Manager',
                svgIcon: 'DocumentManager',
                access: 'canShowMenuItem',
                permissions: ['document-manager-read-write'],
                routes: [
                  {
                    path: '/document/documentmanagerAcknowledge',
                    name: 'Document Acknowldgement Process',
                    access: 'canShowMenuItem',
                    permissions: ['document-manager-read-write'],
                    component: './DocumentManager/DocumentAcknowledgeProcess',
                  },
                  {
                    path: '/documentmanager',
                    name: 'Employee Documents',
                    access: 'canShowMenuItem',
                    permissions: ['document-manager-read-write'],
                    component: './DocumentManager',
                  },
                  {
                    path: '/document/document-generator',
                    name: 'Share Letter By HR',
                    access: 'canShowMenuItem',
                    permissions: ['document-manager-read-write'],
                    component: './DocumentManager/DocumentGenerator',
                  },
                  {
                    path: '/document/documentmanagerAcknowledge/reports',
                    name: 'Reports',
                    permissions: ['document-manager-read-write'],
                    component: './DocumentManager/documentManagerReport',
                    hideInMenu: true,
                  },
                ],
              },
              {
                path: '/leave',
                name: 'Leave Management',
                svgIcon: 'Leave',
                access: 'canShowMenuItem',
                permissions: [
                  'attendance-employee-access',
                  'employee-leave-request-access',
                  'assign-leave',
                  'admin-leave-request-access',
                  'leave-entitlement-report-access',
                  'apply-leave-for-employees',
                ],
                routes: [
                  {
                    path: '/leave/apply-leave-for-employees',
                    component: './Leaves/ApplyTeamLeave/index',
                    name: 'Apply Team Leave',
                    access: 'canShowMenuItem',
                    permissions: ['apply-team-leave'],
                  },
                  {
                    path: '/leave/leave-covering-request',
                    component: './Leaves/LeaveCoveringRequest/index',
                    name: 'Leave Covering Requests',
                    access: 'canShowMenuItem',
                    permissions: ['employee-leave-request-access'],
                  },
                  {
                    path: '/leave/assign-leave',
                    component: './Leaves/AssignLeave/index',
                    name: 'Assign Pre Approved Leave',
                    access: 'canShowMenuItem',
                    permissions: ['assign-leave'],
                  },
                  {
                    path: '/leave/admin-leave-request',
                    component: './AttendanceManager/adminLeaveRequest',
                    name: 'Employee Leaves',
                    access: 'canShowMenuItem',
                    permissions: ['admin-leave-request-access'],
                  },
                  {
                    path: '/leave/leave-entitlements',
                    component: './LeaveEntitlements',
                    name: 'Leave Entitlements',
                    access: 'canShowMenuItem',
                    permissions: ['leave-entitlement-write'],
                  },
                  {
                    path: '/leave/leave-entitlements/new',
                    hideInMenu: true,
                    name: 'Add Leave entitlements',
                    component: './LeaveEntitlements/NewTemplate',
                  },
                  {
                    path: '/leave/leave-reports',
                    component: './AttendanceManager/Report/leaveEntitlementUsage',
                    name: 'Leave Reports',
                    access: 'canShowMenuItem',
                    permissions: ['leave-entitlement-report-access'],
                  },
                ],
              },
              {
                path: '/ess',
                name: 'Employee Self Service',
                svgIcon: 'MyInfo',
                access: 'canShowMenuItem',
                // permissions: [
                //   'my-profile',
                //   'attendance-employee-access',
                //   'employee-leave-request-access',
                //   'my-request',
                // ],
                permissions: [
                  'my-leave-request',
                  'my-attendance',
                  'my-info-view',
                  'my-info-request',
                  'my-request-status',
                  'my-leaves',
                  'my-leave-entitlements',
                  'my-resignation-request',
                  'my-claim-request',
                  'my-post-ot-request',
                ],
                routes: [
                  {
                    path: '/ess/apply-leave',
                    component: './Leaves/ApplyLeave/index',
                    name: 'My Leave Request',
                    access: 'canShowMenuItem',
                    // permissions: ['attendance-employee-access', 'my-leave-request'],
                    permissions: ['my-leave-request'],
                  },
                  {
                    path: '/ess/employee',
                    component: './AttendanceManager/attendanceEmployee',
                    name: 'My Attendance',
                    access: 'canShowMenuItem',
                    // permissions: ['attendance-employee-access', 'my-attendance'],
                    permissions: ['my-attendance'],
                  },
                  {
                    path: '/ess/my-info-view',
                    name: 'My Info View',
                    access: 'canShowMenuItem',
                    component: './MyInfoView',
                    // permissions: ['my-profile', 'my-info-view'],
                    permissions: ['my-info-view'],
                  },
                  {
                    path: '/ess/my-info-request',
                    name: 'My Info Request',
                    access: 'canShowMenuItem',
                    component: './MyInfo',
                    // permissions: ['my-profile', 'my-info-request'],
                    permissions: ['my-info-request'],
                  },
                  {
                    path: '/ess/my-requests',
                    name: 'My Request Status',
                    svgIcon: 'EmployeeRequests',
                    access: 'canShowMenuItem',
                    component: './MyRequest',
                    // permissions: ['my-request', 'my-request-status'],
                    permissions: ['my-request-status'],
                  },
                  {
                    path: '/ess/employee-leave-request',
                    component: './AttendanceManager/employeeLeaveRequest',
                    name: 'My Leaves',
                    access: 'canShowMenuItem',
                    // permissions: ['employee-leave-request-access', 'my-leaves'],
                    permissions: ['my-leaves'],
                  },
                  {
                    name: 'My Leave Entitlements',
                    path: '/ess/my-leave-entitlements',
                    component: './MyLeaveEntitlement',
                    access: 'canShowMenuItem',
                    // permissions: ['attendance-employee-access', 'my-leave-entitlements'],
                    permissions: ['my-leave-entitlements'],
                  },
                  {
                    name: 'My Resignation Request',
                    path: '/ess/my-resignation-request',
                    component: './MyResignationRequest',
                    access: 'canShowMenuItem',
                    // permissions: ['resignation-employee-access', 'my-resignation-request'],
                    permissions: ['my-resignation-request'],
                  },
                  {
                    name: 'My Claim Request',
                    path: '/ess/my-claim-request',
                    component: './MyClaimRequest',
                    access: 'canShowMenuItem',
                    // permissions: ['claim-request-employee-access', 'my-claim-request'],
                    permissions: ['my-claim-request'],
                  },
                  {
                    name: 'My Post OT Request',
                    path: '/ess/my-post-ot-request',
                    component: './MyPostOtRequests',
                    access: 'canShowMenuItem',
                    // permissions: ['post-ot-request-employee-access', 'my-post-ot-request'],
                    permissions: ['my-post-ot-request'],
                  },
                ],
              },
              {
                path: '/manager-self-service',
                name: 'Manager Self Service',
                svgIcon: 'TeamInfo',
                access: 'canShowMenuItem',
                permissions: [
                  'my-teams-read',
                  'my-teams-write',
                  'attendance-manager-access',
                  'enable-employee-requests',
                  'manager-leave-request-access',
                ],
                routes: [
                  {
                    path: '/manager-self-service/manager',
                    component: './AttendanceManager/attendanceManager',
                    name: 'Team Time Sheet',
                    access: 'canShowMenuItem',
                    permissions: ['attendance-manager-access'],
                  },
                  {
                    path: '/manager-self-service/my-teams',
                    name: 'My Team',
                    component: './MyTeams',
                    access: 'canShowMenuItem',
                    permissions: ['my-teams-read', 'my-teams-write'],
                  },
                  {
                    path: '/manager-self-service/user-requests',
                    name: 'Team Request status',
                    svgIcon: 'EmployeeRequests',
                    access: 'canShowMenuItem',
                    permissions: ['enable-employee-requests'],
                    component: './UserRequests',
                  },
                  {
                    path: '/manager-self-service/manager-leave-request',
                    component: './AttendanceManager/managerLeaveRequest',
                    name: 'Team Leaves',
                    access: 'canShowMenuItem',
                    permissions: ['manager-leave-request-access'],
                  },
                  {
                    name: 'Edit Employee',
                    path: '/manager-self-service/my-teams/employee/:id',
                    hideInMenu: true,
                    component: './MyTeams/MyTeamEditEmployee',
                  },
                ],
              },
              {
                path: '/attendance-manager',
                name: 'Attendance',
                svgIcon: 'Attendance',
                access: 'canShowMenuItem',
                permissions: [
                  'attendance-admin-access',
                  'shift-change',
                  'invalid-attendance-update-admin-access',
                ],
                routes: [
                  {
                    path: '/attendance-manager/admin',
                    component: './AttendanceManager/attendanceAdmin',
                    name: 'Employee Time Sheet',
                    access: 'canShowMenuItem',
                    permissions: ['attendance-admin-access'],
                  },
                  {
                    path: '/attendance-manager/employees-invalid-attendance',
                    component: './AttendanceManager/employeeInvalidAttendance',
                    name: 'Employee Invalid Time Sheet',
                    access: 'canShowMenuItem',
                    permissions: ['invalid-attendance-update-admin-access'],
                  },
                  {
                    path: '/attendance-manager/summary',
                    component: './AttendanceManager/attendanceSummary',
                    name: 'Summary View of the Day',
                    hideInMenu: true,
                  },
                  {
                    path: '/attendance-manager/shift-change',
                    name: 'Shift Change',
                    access: 'canShowMenuItem',
                    permissions: ['shift-change'],
                    component: './shiftChange',
                  },
                  {
                    path: '/attendance-manager/attendance-report',
                    component: './AttendanceManager/Report/attendanceReports',
                    name: 'Attendance Reports',
                    access: 'canShowMenuItem',
                    permissions: ['attendance-admin-access'],
                  },
                ],
              },
              {
                path: '/employee-journey',
                name: 'Employee Journey',
                svgIcon: 'TeamInfo',
                access: 'canShowMenuItem',
                permissions: ['employee-write'],
                routes: [
                  {
                    path: '/employee-journey/employee-journey-update',
                    name: 'Employee Journey Update',
                    permissions: ['employee-write'],
                    component: './EmployeeJourneyUpdate',
                  },
                  {
                    path: '/employee-journey/rehire-process',
                    name: 'Rehire Process',
                    permissions: ['employee-write'],
                    component: './EmployeeRehireProcess',
                  },
                  {
                    path: '/employee-journey/bulk-promotion',
                    name: 'Bulk Promotion',
                    permissions: ['employee-write'],
                    component: './EmployeeJourneyUpdate/BulkUploader/Promotion',
                  },
                  {
                    path: '/employee-journey/bulk-transfer',
                    name: 'Bulk Transfer',
                    permissions: ['employee-write'],
                    component: './EmployeeJourneyUpdate/BulkUploader/Transfer',
                  },
                ],
              },
              {
                path: '/payroll',
                name: 'Payroll',
                svgIcon: 'Payroll',
                access: 'canShowMenuItem',
                permissions: ['payroll-read-write'],
                routes: [
                  {
                    path: '/payroll/increment-uploader',
                    name: 'Increment Uploader',
                    permissions: ['payroll-read-write'],
                    component: './SalaryIncrementUploader',
                  },
                ],
              },
              {
                path: '/work-schedule',
                name: 'Work Schedule',
                svgIcon: 'WorkSchedule',
                access: 'canShowMenuItem',
                permissions: ['work-schedule-read-write'],
                component: './WorkSchedule',
              },
              // {
              //   path: '/notices',
              //   name: 'Notices',
              //   svgIcon: 'Notices',
              //   access: 'canShowMenuItem',
              //   permissions: ['company-notice-read-write', 'team-notice-read-write'],
              //   routes: [
              //     {
              //       path: '/notices',
              //       name: 'Notice Builder',
              //       svgIcon: 'Notices',
              //       access: 'canShowMenuItem',
              //       permissions: ['company-notice-read-write', 'team-notice-read-write'],
              //       component: './Notice',
              //     },
              //     {
              //       path: '/notices/create',
              //       name: 'Add Notice',
              //       permissions: ['company-notice-read-write', 'team-notice-read-write'],
              //       component: './Notice/NoticeForm',
              //       hideInMenu: true,
              //     },
              //     {
              //       path: '/notices/:id',
              //       name: 'Edit Notice',
              //       permissions: ['company-notice-read-write', 'team-notice-read-write'],
              //       component: './Notice/NoticeForm',
              //       hideInMenu: true,
              //     },
              //   ],
              // },
              {
                path: '/notices',
                name: 'Notice Builder',
                svgIcon: 'Notices',
                access: 'canShowMenuItem',
                permissions: ['company-notice-read-write', 'team-notice-read-write'],
                component: './Notice',
              },
              {
                path: '/notices/create',
                name: 'Add Notice',
                permissions: ['company-notice-read-write', 'team-notice-read-write'],
                component: './Notice/NoticeForm',
                hideInMenu: true,
              },
              {
                path: '/notices/:id',
                name: 'Edit Notice',
                permissions: ['company-notice-read-write', 'team-notice-read-write'],
                component: './Notice/NoticeForm',
                hideInMenu: true,
              },
              {
                path: '/report-engine',
                name: 'Reports',
                svgIcon: 'Reports',
                access: 'canShowMenuItem',
                permissions: ['reports-read-write'],
                routes: [
                  {
                    path: '/report-engine',
                    name: 'HR Reports',
                    svgIcon: 'Reports',
                    access: 'canShowMenuItem',
                    permissions: ['reports-read-write'],
                    component: './ReportEngine',
                  },
                  {
                    path: '/report-engine/report-wizard/new',
                    component: './ReportEngine/NewReport',
                    name: 'Add Report',
                    permissions: ['reports-read-write'],
                    hideInMenu: true,
                  },
                  {
                    path: '/report-engine/report-wizard/:id',
                    component: './ReportEngine/NewReport',
                    name: 'Edit Report',
                    permissions: ['reports-read-write'],
                    hideInMenu: true,
                  },
                  {
                    path: '/report-engine/get-report/:reportId',
                    component: './ReportEngine/ViewReport',
                    name: 'View Report',
                    permissions: ['reports-read-write'],
                    hideInMenu: true,
                  },
                  {
                    path: '/report-engine/audit-trail',
                    name: 'Audit Trail',
                    access: 'canShowMenuItem',
                    permissions: ['reports-read-write'],
                    component: './AuditTrail',
                  },
                ],
              },
              {
                path: '/settings/leave-types',
                access: 'canShowMenuItem',
                name: 'Leave Types',
                hideInMenu: true,
                component: './AttendanceManager/LeaveType',
                permissions: ['leave-type-config'],
              },
              {
                path: '/settings/leave-types/config/:id',
                component: './AttendanceManager/components/Config',
                name: 'Configuration',
                hideInMenu: true,
                access: 'canShowMenuItem',
                permissions: ['leave-type-config'],
              },
              {
                path: '/my-work-schedule',
                name: 'My Work Schedule',
                svgIcon: 'MyWorkSchedule',
                access: 'canShowMenuItem',
                permissions: ['my-work-schedule'],
                component: './MyWorkSchedule',
              },
              {
                path: '/settings',
                name: 'Settings',
                svgIcon: 'Settings',
                access: 'canShowMenuItem',
                component: './Settings',
                permissions: [
                  'user-read-write',
                  'master-data-write',
                  'access-levels-read-write',
                  'company-info-read-write',
                  'manual-process',
                ],
                hideInMenu: true,
              },
              {
                path: '/settings/users',
                name: 'Users',
                hideInMenu: true,
                access: 'canShowMenuItem',
                permissions: ['user-read-write'],
                component: './User',
              },
              {
                path: '/settings/accesslevels',
                name: 'User Roles',
                hideInMenu: true,
                access: 'canShowMenuItem',
                permissions: ['access-levels-read-write'],
                component: './UserRole',
              },
              {
                path: '/settings/accesslevels/createrole',
                hideInMenu: true,
                name: 'Create User Role',
                component: './UserRole/subpage/createUserRole',
              },
              {
                path: '/settings/accesslevels/editrole/:id',
                hideInMenu: true,
                name: 'Edit User Role',
                component: './UserRole/subpage/editUserRole',
              },
              {
                path: '/settings/master-data/:id',
                name: 'Master Data',
                hideInMenu: true,
                access: 'canShowMenuItem',
                permissions: ['master-data-write'],
                component: './EmployeeFeild',
              },
              {
                path: '/settings/employee-journey-configurations/:id',
                name: 'Employee Journey Configurations',
                hideInMenu: true,
                access: 'canShowMenuItem',
                permissions: ['master-data-write'],
                component: './EmployeeJourneyUpdate/SettingsCard',
              },
              {
                path: '/settings/work-patterns',
                svgIcon: 'FieldTimeOutlined',
                name: 'Work Patterns',
                access: 'canShowMenuItem',
                hideInMenu: true,
                permissions: ['work-pattern-read-write'],
                component: './WorkPattern',
              },
              {
                path: '/settings/work-patterns/new',
                component: './WorkPattern/NewWorkPattern',
                name: 'Add Work Pattern',
                hideInMenu: true,
              },
              {
                path: '/settings/work-patterns/:id',
                component: './WorkPattern/EditWorkPattern',
                name: 'Edit Work Pattern',
                hideInMenu: true,
              },
              {
                path: '/settings/work-calander',
                name: 'Work Calendar',
                hideInMenu: true,
                component: './WorkCalendar',
                permissions: ['work-calendar-read-write'],
                access: 'canShowMenuItem',
              },
              {
                path: '/settings/work-calander-day-type',
                name: 'Day Type',
                hideInMenu: true,
                component: './WorkCalendarDayType',
                permissions: ['work-calendar-day-type-read-write'],
                access: 'canShowMenuItem',
              },
              {
                path: '/settings/pay-type',
                name: 'Pay Type',
                hideInMenu: true,
                component: './PayTypes',
                permissions: ['pay-type-read-write'],
                access: 'canShowMenuItem',
              },
              {
                path: '/settings/bulk-upload',
                name: 'Bulk Upload',
                hideInMenu: true,
                permissions: ['bulk-upload-read-write'],
                access: 'canShowMenuItem',
                component: './BulkUpload',
              },
              {
                path: '/settings/self-service-lock',
                name: 'Self Service Lock',
                hideInMenu: true,
                permissions: ['self-service-lock'],
                access: 'canShowMenuItem',
                component: './SelfServiceLock',
              },
              {
                path: '/settings/bulk-upload/viewHistory',
                component: './BulkUpload/viewHistory',
                name: 'View History',
                permissions: ['bulk-upload-read-write'],
                hideInMenu: true,
              },
              {
                path: '/settings/manual-processes',
                name: 'Manual Processes',
                hideInMenu: true,
                access: 'canShowMenuItem',
                permissions: ['manual-process'],
                component: './ManualProcesses',
              },
              {
                path: '/settings/manual-processes/:type/history',
                component: './ManualProcesses/viewHistory',
                name: 'History',
                hideInMenu: true,
              },
              {
                path: '/settings/manual-processes/viewHistory',
                component: './ManualProcesses/viewHistory',
                name: 'View History',
                hideInMenu: true,
              },
              {
                path: '/settings/scheduled-jobs-log',
                name: 'Scheduled Jobs Log',
                access: 'canShowMenuItem',
                component: './ScheduledJobsLog',
                permissions: ['scheduled-jobs-log'],
                hideInMenu: true,
              },
              {
                path: '/settings/document-templates',
                hideInMenu: true,
                component: './DocumentTemplate',
                name: 'Letter Template Builder',
              },
              {
                path: '/settings/document-templates/new',
                hideInMenu: true,
                name: 'Add Letter Template',
                component: './DocumentTemplate/NewTemplate',
              },
              {
                path: '/settings/document-templates/:id',
                hideInMenu: true,
                name: 'Edit Letter Template',
                component: './DocumentTemplate/NewTemplate',
              },
              {
                path: '/settings/email-notifications',
                svgIcon: 'EmailTemplate',
                hideInMenu: true,
                name: 'Email Notifications',
                access: 'canShowMenuItem',
                permissions: ['email-template-read-write'],
                component: './EmailTemplate',
              },
              {
                path: '/settings/email-notifications/new',
                component: './EmailTemplate/NewTemplate',
                name: 'Add Email Notification',
                permissions: ['email-template-read-write'],
                hideInMenu: true,
              },
              {
                path: '/settings/email-notifications/:id',
                component: './EmailTemplate/NewTemplate',
                name: 'Edit Email Notification',
                permissions: ['email-template-read-write'],
                hideInMenu: true,
              },

              {
                path: '/settings/workflow-engine',
                name: 'Workflow Management',
                svgIcon: 'ToolOutlined',
                hideInMenu: true,
                access: 'canShowMenuItem',
                permissions: ['workflow-management-read-write'],
                component: './WorkflowManagement',
              },
              {
                path: '/settings/expense-module',
                name: 'Expense Management Configuration',
                svgIcon: 'ToolOutlined',
                hideInMenu: true,
                access: 'canShowMenuItem',
                permissions: ['expense-management-read-write'],
                component: './ExpenseManagement',
              },
              {
                path: '/settings/edit-company-info',
                name: 'Company Information',
                hideInMenu: true,
                access: 'canShowMenuItem',
                permissions: ['company-info-read-write'],
                component: './CompanyInfo',
              },
              {
                name: 'Form Builder',
                path: '/settings/form-builder',
                hideInMenu: true,
                access: 'canShowMenuItem',
                permissions: ['form-builder'],
                component: './FormBuilder',
              },
              {
                name: 'Edit Dynamic Form',
                path: '/settings/form-builder/:modelPath*',
                hideInMenu: true,
                access: 'canShowMenuItem',
                permissions: ['form-builder'],
                component: './FormBuilder/edit',
              },
              {
                name: 'Template Builder',
                path: '/settings/template-builder',
                hideInMenu: true,
                access: 'canShowMenuItem',
                permissions: ['template-builder'],
                component: './TemplateBuilder',
              },
              {
                name: 'Workflow Builder',
                path: '/settings/workflow-builder',
                hideInMenu: true,
                access: 'canShowMenuItem',
                permissions: ['template-builder'],
                component: './WorkflowBuilder',
              },
              {
                name: 'Workflow Builder',
                path: '/settings/workflow-builder/:id',
                hideInMenu: true,
                access: 'canShowMenuItem',
                permissions: ['template-builder'],
                component: './WorkflowBuilder/workflowConfig',
              },
              {
                name: 'Financial Year Configurations',
                path: '/settings/financial-year',
                hideInMenu: true,
                access: 'canShowMenuItem',
                permissions: ['financial-year-read-write'],
                component: './FinancialYear',
              },
              {
                path: '/settings/template-builder/create',
                name: 'Create',
                permissions: ['template-builder'],
                component: './TemplateBuilder/templateBuilderForm',
                hideInMenu: true,
              },
              {
                name: 'Form Template Executor',
                path: '/template-builder/:id/interactive-viewer',
                component: './TemplateBuilder/executor',
                hideInMenu: true,
              },
              {
                name: 'Edit Form Template',
                path: '/settings/template-builder/:id*',
                hideInMenu: true,
                access: 'canShowMenuItem',
                permissions: ['template-builder'],
                component: './TemplateBuilder/templateBuilderForm',
              },
              {
                path: 'documentmanager/:slugs*',
                hideInMenu: true,
                access: 'canShowMenuItem',
                permissions: ['document-manager-read-write'],
                component: './DocumentManager',
              },
              {
                path: '/settings/work-shifts',
                name: 'Work Shifts',
                access: 'canShowMenuItem',
                hideInMenu: true,
                permissions: ['work-shifts-read-write'],
                component: './WorkShifts',
              },
              {
                path: '/settings/work-shifts/new',
                hideInMenu: true,
                name: 'Add Work Shift',
                component: './WorkShifts/NewWorkShift',
              },
              {
                path: '/settings/work-shifts/:id',
                hideInMenu: true,
                name: 'Edit  Work Shift',
                component: './WorkShifts/NewWorkShift',
              },
              {
                path: '/settings/shifts-assign',
                name: 'Shift Assign',
                access: 'canShowMenuItem',
                hideInMenu: true,
                permissions: ['shifts-assign-read-write'],
                component: './ShiftAssign',
              },
              {
                path: '/settings/work-pattern-assign',
                name: 'Work Pattern Assign',
                access: 'canShowMenuItem',
                hideInMenu: true,
                permissions: ['work-pattern-assign-read-write'],
                component: './WorkPatternAssign',
              },
              {
                path: '/settings/employee-number',
                name: 'Employee Number Configuration',
                access: 'canShowMenuItem',
                component: './EmployeeNumberConfig',
                permissions: ['employee-create', 'employee-write'],
                hideInMenu: true,
              },
              {
                path: '/settings/config-resignation-process',
                name: 'Resignation Process Configuration',
                access: 'canShowMenuItem',
                component: './ResignationProcessConfig',
                permissions: ['config-resignation-process-read-write'],
                hideInMenu: true,
              },
              {
                path: '/settings/config-resignation-process/new',
                hideInMenu: true,
                name: 'Setup Resignation Process',
                component: './ResignationProcessConfig/resignationProcess',
              },
              {
                path: '/settings/config-resignation-process/:id',
                hideInMenu: true,
                name: 'Edit Resignation Process',
                component: './ResignationProcessConfig/resignationProcess',
              },
              {
                path: '/settings/config-confirmation-process',
                name: 'Confirmation Process Configuration',
                access: 'canShowMenuItem',
                component: './ConfirmationProcessConfig',
                permissions: ['config-confirmation-process-read-write'],
                hideInMenu: true,
              },
              {
                path: '/settings/config-confirmation-process/new',
                hideInMenu: true,
                name: 'Setup Confirmation Process',
                component: './ConfirmationProcessConfig/confirmationProcess',
              },
              {
                path: '/settings/config-confirmation-process/:id',
                hideInMenu: true,
                name: 'Edit Confirmation Process',
                component: './ConfirmationProcessConfig/confirmationProcess',
              },
              {
                name: 'Change Password',
                path: '/changePassword/:id',
                component: './Auth/ChangePassword',
                hideInMenu: true,
              },
              {
                path: '/todo',
                name: 'To Do',
                permissions: ['admin-widget', 'employee-widget', 'manager-widget'],
                component: './ToDo',
                hideInMenu: true,
              },
              {
                path: '/settings/azure-active-directory',
                name: 'Azure Active Directory',
                access: 'canShowMenuItem',
                component: './ImportAzureUsers',
                permissions: ['azure-active-directory'],
                hideInMenu: true,
              },
              {
                path: '/settings/billing',
                name: 'Billing',
                svgIcon: 'Payroll',
                access: 'canShowMenuItem',
                component: './Billing',
                permissions: ['billing'],
                hideInMenu: true,
              },
              {
                path: '/403',
                component: './403',
                name: 'Permission Denied',
                hideInMenu: true,
              },
              {
                component: './404',
              },
            ],
          },
          {
            component: './404',
          },
        ],
      },
    ],
  },
  {
    component: './404',
  },
];
