<?php

return [
    // list of time change request tokens
    'time-change-request' => [
        "employee_first_name" => 'First Name of rquested employee',
        "employee_last_name" => 'Last Name of rquested employee',
        "employee_full_name" => 'Full Name of rquested employee',
        "employee_number" => 'Employee Number of rquested employee',
        "in_date_time" => 'Clock In Date Time',
        "out_date_time" => 'Clock Out Date Time',
        "reason" => 'Reason',
        "recipient_first_name" => 'Recipient First Name',
        "recipient_last_name" => 'Recipient Last Name',
        "recipient_full_name" => 'Recipient Full Name',
        "recipient_email" => 'Recipient Email',
        "workflow_action" => 'Perform Action',
        "workflow_action_performer_first_name" => 'Action Performer First Name',
        "workflow_action_performer_last_name" => 'Action Performer Last Name',
        "workflow_action_performer_full_name" => 'Action Performer Full Name'
    ],
    // list of leave request tokens
    'leave-request' => [
        "employee_first_name" => 'First Name of rquested employee',
        "employee_last_name" => 'Last Name of rquested employee',
        "employee_full_name" => 'Full Name of rquested employee',
        "employee_number" => 'Employee Number of rquested employee',
        "leave_from_date_time" => 'From Date And Time',
        "leave_to_date_time" => 'To Date And Time',
        "leave_type" => 'Leave Type',
        "leave_period_type" => 'Leave Period Type',
        "num_of_leave_dates" => 'Number Of Leave Days',
        "reason" => 'Reason',
        "recipient_first_name" => 'Recipient First Name',
        "recipient_last_name" => 'Recipient Last Name',
        "recipient_full_name" => 'Recipient Full Name',
        "recipient_email" => 'Recipient Email',
        "workflow_action" => 'Perform Action',
        "workflow_action_performer_first_name" => 'Action Performer First Name',
        "workflow_action_performer_last_name" => 'Action Performer Last Name',
        "workflow_action_performer_full_name" => 'Action Performer Full Name'
    ],
    // list of profile update request tokens
    'profile-update-request' => [
        "employee_first_name" => 'First Name of rquested employee',
        "employee_last_name" => 'Last Name of rquested employee',
        "employee_full_name" => 'Full Name of rquested employee',
        "employee_number" => 'Employee Number of rquested employee',
        "related_section" => 'Related Section',
        "related_action" => 'Related Action',
        "recipient_first_name" => 'Recipient First Name',
        "recipient_last_name" => 'Recipient Last Name',
        "recipient_full_name" => 'Recipient Full Name',
        "recipient_email" => 'Recipient Email',
        "workflow_action" => 'Perform Action',
        "workflow_action_performer_first_name" => 'Action Performer First Name',
        "workflow_action_performer_last_name" => 'Action Performer Last Name',
        "workflow_action_performer_full_name" => 'Action Performer Full Name'
        
    ],
    // list of short leave request tokens
    'short_leave-request' => [
        "employee_first_name" => 'First Name of rquested employee',
        "employee_last_name" => 'Last Name of rquested employee',
        "employee_full_name" => 'Full Name of rquested employee',
        "employee_number" => 'Employee Number of rquested employee',
        "short_leave_date" => 'Short Leave Date',
        "short_leave_from_time" => 'Short Leave From Time',
        "short_leave_end_time" => 'Short Leave End Time',
        "reason" => 'Reason',
        "leave_type" => 'Leave Type',
        "recipient_first_name" => 'Recipient First Name',
        "recipient_last_name" => 'Recipient Last Name',
        "recipient_full_name" => 'Recipient Full Name',
        "recipient_email" => 'Recipient Email',
        "workflow_action" => 'Perform Action',
        "workflow_action_performer_first_name" => 'Action Performer First Name',
        "workflow_action_performer_last_name" => 'Action Performer Last Name',
        "workflow_action_performer_full_name" => 'Action Performer Full Name'
    ],
    // list of shift change request tokens
    'shift-change-request' => [
        "employee_first_name" => 'First Name of rquested employee',
        "employee_last_name" => 'Last Name of rquested employee',
        "employee_full_name" => 'Full Name of rquested employee',
        "employee_number" => 'Employee Number of rquested employee',
        "shift_change_applicable_date" => 'Shift Change Applicable Date',
        "previous_shift" => 'Previous Shift',
        "new_shift" => 'New Shift',
        "reason" => 'Reason',
        "recipient_first_name" => 'Recipient First Name',
        "recipient_last_name" => 'Recipient Last Name',
        "recipient_full_name" => 'Recipient Full Name',
        "recipient_email" => 'Recipient Email',
        "workflow_action" => 'Perform Action',
        "workflow_action_performer_first_name" => 'Action Performer First Name',
        "workflow_action_performer_last_name" => 'Action Performer Last Name',
        "workflow_action_performer_full_name" => 'Action Performer Full Name'
    ],
    // list of cancel leave request tokens
    'cancel_leave-request' => [
        "employee_first_name" => 'First Name of rquested employee',
        "employee_last_name" => 'Last Name of rquested employee',
        "employee_full_name" => 'Full Name of rquested employee',
        "employee_number" => 'Employee Number of rquested employee',
        "original_leave_from_date" => 'Original Leave From Date',
        "original_leave_end_date" => 'Orginal Leave End Date',
        // "leave_type" => 'Leave Type',
        // "leave_period_type" => 'Leave Period Type',
        "applied_leave_count" => 'Applied Leave Count',
        "cancelled_leave_count" => 'Cancelled Leave Count',
        "reason" => 'Reason',
        "recipient_first_name" => 'Recipient First Name',
        "recipient_last_name" => 'Recipient Last Name',
        "recipient_full_name" => 'Recipient Full Name',
        "recipient_email" => 'Recipient Email',
        "workflow_action" => 'Perform Action',
        "workflow_action_performer_first_name" => 'Action Performer First Name',
        "workflow_action_performer_last_name" => 'Action Performer Last Name',
        "workflow_action_performer_full_name" => 'Action Performer Full Name'
    ],
    // list of resignation request tokens
    'resignation-request' => [
        "employee_first_name" => 'First Name of rquested employee',
        "employee_last_name" => 'Last Name of rquested employee',
        "employee_full_name" => 'Full Name of rquested employee',
        "employee_number" => 'Employee Number of rquested employee',
        "resignation_handover_date" => 'Resignation Handover Date',
        "resignation_last_working_date" => 'Last Working Date',
        "resignation_effective_date" => 'Resignation Effective Date',
        "resignation_type" => 'Resignation Type',
        "resignation_notice_period_complete_status" => 'Notice Period Complete Status',
        "reason" => 'Reason',
        "recipient_first_name" => 'Recipient First Name',
        "recipient_last_name" => 'Recipient Last Name',
        "recipient_full_name" => 'Recipient Full Name',
        "recipient_email" => 'Recipient Email',
        "workflow_action" => 'Perform Action',
        "workflow_action_performer_first_name" => 'Action Performer First Name',
        "workflow_action_performer_last_name" => 'Action Performer Last Name',
        "workflow_action_performer_full_name" => 'Action Performer Full Name'
    ],
    // list of cancel short leave request tokens
    'cancel-short-leave-request' => [
        "employee_first_name" => 'First Name of rquested employee',
        "employee_last_name" => 'Last Name of rquested employee',
        "employee_full_name" => 'Full Name of rquested employee',
        "employee_number" => 'Employee Number of rquested employee',
        "short_leave_date" => 'Short Leave Date',
        "short_leave_from_time" => 'Short Leave From Time',
        "short_leave_end_time" => 'Short Leave End Time',
        "reason" => 'Reason',
        "leave_type" => 'Leave Type',
        "recipient_first_name" => 'Recipient First Name',
        "recipient_last_name" => 'Recipient Last Name',
        "recipient_full_name" => 'Recipient Full Name',
        "recipient_email" => 'Recipient Email',
        "workflow_action" => 'Perform Action',
        "workflow_action_performer_first_name" => 'Action Performer First Name',
        "workflow_action_performer_last_name" => 'Action Performer Last Name',
        "workflow_action_performer_full_name" => 'Action Performer Full Name'
    ],
    // list of cancel short leave request tokens
    'claim-request' => [
        "employee_first_name" => 'First Name of rquested employee',
        "employee_last_name" => 'Last Name of rquested employee',
        "employee_full_name" => 'Full Name of rquested employee',
        "employee_number" => 'Employee Number of rquested employee',
        "claim_type" => 'Claim Type',
        "financial_year" => 'Financial Year',
        "total_receipt_amount" => 'Total Receipt Amount',
        "claim_month" => 'Claim Month',
        "recipient_first_name" => 'Recipient First Name',
        "recipient_last_name" => 'Recipient Last Name',
        "recipient_full_name" => 'Recipient Full Name',
        "recipient_email" => 'Recipient Email',
        "workflow_action" => 'Perform Action',
        "workflow_action_performer_first_name" => 'Action Performer First Name',
        "workflow_action_performer_last_name" => 'Action Performer Last Name',
        "workflow_action_performer_full_name" => 'Action Performer Full Name'
    ],
    // list of post ot request tokens
    'post-ot-request' => [
        "employee_first_name" => 'First Name of rquested employee',
        "employee_last_name" => 'Last Name of rquested employee',
        "employee_full_name" => 'Full Name of rquested employee',
        "employee_number" => 'Employee Number of rquested employee',
        "post_ot_request_month" => 'Requested Month',
        "post_ot_request_year" => 'Requested Year',
        "total_requested_ot" => 'Total Requested OT',
        "total_approved_ot" => 'Total Approved OT',
        "num_of_requested_dates" => 'Number of Requested Dates',
        "recipient_first_name" => 'Recipient First Name',
        "recipient_last_name" => 'Recipient Last Name',
        "recipient_full_name" => 'Recipient Full Name',
        "recipient_email" => 'Recipient Email',
        "workflow_action" => 'Perform Action',
        "workflow_action_performer_first_name" => 'Action Performer First Name',
        "workflow_action_performer_last_name" => 'Action Performer Last Name',
        "workflow_action_performer_full_name" => 'Action Performer Full Name'
    ]
];
